source 'https://rubygems.org'

gem "ocean-rails", git: "git://github.com/OceanDev/ocean-rails.git"
gem "rails", "~> 4.0"
gem "mysql2"
gem "foreigner"
gem "jbuilder"

group :test, :development do
  gem "sqlite3"
  gem "memory_test_fix"
  gem "rspec-rails", "~> 2.0"
  gem "simplecov", require: false
  gem "factory_girl_rails", "~> 4.0"
  gem "immigrant"
  gem "annotate", ">=2.5.0"
end

gem "protected_attributes"
